# MongoDB Config
spring.mongodb.uri=mongodb+srv://ManasaSA:MedConnect123@cluster0.skvw6gd.mongodb.net/hospital_db?retryWrites=true&w=majority&appName=Cluster0
spring.mongodb.database=hospital_db

# Server
server.port=8081